### ISSUE TITLE
Authentication pages

### ISSUE THREAD

**Issue by Imadnajam** [Imadnajam/UnderMovies#1]
add a login page on UnderMovies with a design similar to the home page

**Comment by rohit-chaware** [comment]
@Imadnajam I would like to work on this issue.

**Comment by Imadnajam** [comment]
Hello @R4Rohit23 yes you can , When you finish the issue, please send a screenshot.

**Comment by rohit-chaware** [comment]
Sorry @Imadnajam. The project is very complicated and I don't think so I might be able to complete the task.
